pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step"
		    chmod 777 ./gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
		    chmod 777 ./gradlew
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
		    docker build -t "mg" .
		    docker run mg
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage ="
		    docker login -u vikaspmandal -p V9570073669m;
                    docker tag mg vikaspmandal/mg_test
                    docker push vikaspmandal/mg_test
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
	post{
		always{
			deleteDir()
		}
	}
}

